import '../../core/utils/formatters.dart';
import 'ai_summary.dart';

/// Every piece of patient-facing wording about a model result lives here, so the patient,
/// doctor and admin screens say exactly the same thing.
///
/// The model is a current-label classification prototype: its output is a screening pattern,
/// never a diagnosis, and its probability is never a chance of developing diabetes.
abstract final class ScreeningWording {
  static const resultTitle = 'Diabetes Screening Result';

  static String headline(bool positive) => positive ? 'Diabetes-related pattern detected' : 'No diabetes-related pattern detected';

  /// Short form for chips and tables.
  static String short(bool positive) => positive ? 'Pattern detected' : 'No pattern detected';

  static const probabilityLabel = 'Model classification probability';
  static const probabilityCaption =
      'The probability the model assigns to the Positive (diabetes-related pattern) class for these answers. It is not a chance of having or developing diabetes.';

  static const disclaimer =
      'This result is generated by a machine-learning classification model and is intended for screening and informational purposes only. '
      'It is not a medical diagnosis and does not predict future diabetes onset. Please consult a qualified healthcare professional for medical evaluation.';
}

/// The exact 16-field request the diabetes API accepts. Dart names are idiomatic; [toJson]
/// produces the API's column names (with their spaces and casing) in model order.
class DiabetesPredictionRequest {
  const DiabetesPredictionRequest({
    required this.age,
    required this.gender,
    required this.polyuria,
    required this.polydipsia,
    required this.suddenWeightLoss,
    required this.weakness,
    required this.polyphagia,
    required this.genitalThrush,
    required this.visualBlurring,
    required this.itching,
    required this.irritability,
    required this.delayedHealing,
    required this.partialParesis,
    required this.muscleStiffness,
    required this.alopecia,
    required this.obesity,
  });

  static const minAge = 16;
  static const maxAge = 90;

  final int age;

  /// "Male" or "Female".
  final String gender;

  // Each symptom is "Yes" or "No".
  final String polyuria;
  final String polydipsia;
  final String suddenWeightLoss;
  final String weakness;
  final String polyphagia;
  final String genitalThrush;
  final String visualBlurring;
  final String itching;
  final String irritability;
  final String delayedHealing;
  final String partialParesis;
  final String muscleStiffness;
  final String alopecia;
  final String obesity;

  /// Problem with the request, or null when every field holds an accepted value.
  String? validate() {
    if (age < minAge || age > maxAge) return 'Age must be between $minAge and $maxAge.';
    if (gender != 'Male' && gender != 'Female') return 'Gender must be Male or Female.';
    for (final e in toJson().entries.skip(2)) {
      if (e.value != 'Yes' && e.value != 'No') return '${e.key} must be Yes or No.';
    }
    return null;
  }

  Map<String, Object> toJson() => {
        'Age': age,
        'Gender': gender,
        'Polyuria': polyuria,
        'Polydipsia': polydipsia,
        'sudden weight loss': suddenWeightLoss,
        'weakness': weakness,
        'Polyphagia': polyphagia,
        'Genital thrush': genitalThrush,
        'visual blurring': visualBlurring,
        'Itching': itching,
        'Irritability': irritability,
        'delayed healing': delayedHealing,
        'partial paresis': partialParesis,
        'muscle stiffness': muscleStiffness,
        'Alopecia': alopecia,
        'Obesity': obesity,
      };
}

/// A saved assessment: the 16 inputs and the diabetes API's response, stored by the backend.
class DiabetesAssessment {
  const DiabetesAssessment({
    required this.id,
    required this.assessmentCode,
    required this.patientId,
    required this.assessedAt,
    required this.modelVersion,
    required this.inputs,
    required this.prediction,
    this.classificationProbability,
    this.modelName,
    this.resultInterpretation,
    this.disclaimer,
    this.lifestyleSnapshot = const {},
    this.performedByRole,
    this.interpretation,
  });

  final String id;
  final String assessmentCode;
  final String patientId;
  final DateTime assessedAt;

  /// Fingerprint of the model artifact that produced this result.
  final String modelVersion;
  final String? modelName;

  /// Exactly the 16 model inputs, keyed by model column name.
  final Map<String, dynamic> inputs;

  /// Model classification: "Positive" or "Negative".
  final String prediction;

  /// The model's probability for the Positive class, exactly as the API returned it.
  /// NOT a probability of having or developing diabetes.
  final double? classificationProbability;

  /// The API's own interpretation sentence, as shown at the time.
  final String? resultInterpretation;

  /// The API's disclaimer, as shown at the time.
  final String? disclaimer;
  final Map<String, dynamic> lifestyleSnapshot;
  final String? performedByRole;

  /// Optional, separate AI (Gemini) interpretation generated later. Not part of the model result.
  final AISummary? interpretation;

  bool get isPositive => prediction == 'Positive';

  String get headline => ScreeningWording.headline(isPositive);

  String get explanation => resultInterpretation != null
      ? '$resultInterpretation, based on the information provided.'
      : (isPositive
          ? 'Based on the information provided, the diabetes model detected a pattern associated with diabetes.'
          : 'Based on the information provided, the diabetes model did not detect a pattern associated with diabetes.');

  String get disclaimerText => disclaimer ?? ScreeningWording.disclaimer;

  factory DiabetesAssessment.fromJson(Map<String, dynamic> j) => DiabetesAssessment(
        id: j['id'] as String,
        assessmentCode: j['assessment_code'] as String,
        patientId: j['patient_id'] as String,
        assessedAt: parseDate(j['assessed_at'])!,
        modelVersion: j['model_version'] as String,
        modelName: j['model_name'] as String?,
        inputs: Map<String, dynamic>.from(j['inputs'] as Map),
        prediction: j['prediction'] as String,
        classificationProbability: (j['classification_probability'] as num?)?.toDouble(),
        resultInterpretation: j['interpretation'] as String?,
        disclaimer: j['disclaimer'] as String?,
        lifestyleSnapshot: Map<String, dynamic>.from(j['lifestyle_snapshot'] as Map? ?? const {}),
        performedByRole: j['performed_by_role'] as String?,
        interpretation: j['ai_interpretation'] == null ? null : AISummary.fromJson(j['ai_interpretation'] as Map<String, dynamic>),
      );
}

/// Non-sensitive metadata about the model serving assessments.
class DiabetesModelInfo {
  const DiabetesModelInfo({this.modelName, this.modelVersion, this.limitation, this.validation = const {}, this.ageMin, this.ageMax});
  final String? modelName;
  final String? modelVersion;
  final String? limitation;
  final Map<String, dynamic> validation;
  final int? ageMin;
  final int? ageMax;

  factory DiabetesModelInfo.fromJson(Map<String, dynamic> j) {
    final dataset = j['dataset_info'] as Map<String, dynamic>?;
    return DiabetesModelInfo(
      modelName: j['model_name'] as String?,
      modelVersion: j['model_version'] as String?,
      limitation: j['limitation'] as String?,
      validation: Map<String, dynamic>.from(j['validation'] as Map? ?? const {}),
      ageMin: (dataset?['age_min'] as num?)?.toInt(),
      ageMax: (dataset?['age_max'] as num?)?.toInt(),
    );
  }
}
